"""modified property model

Revision ID: 223f31809fac
Revises: b87ba7d823cb
Create Date: 2024-05-18 22:20:50.468980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '223f31809fac'
down_revision = 'b87ba7d823cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_column('parking')
        batch_op.drop_column('lot_size')
        batch_op.drop_column('loading_docks')
        batch_op.drop_column('property_condition')
        batch_op.drop_column('security')
        batch_op.drop_column('warehouse_size')
        batch_op.drop_column('zoning')
        batch_op.drop_column('investment_potential')
        batch_op.drop_column('accessibility')
        batch_op.drop_column('year_built')
        batch_op.drop_column('utilities')
        batch_op.drop_column('type_style')
        batch_op.drop_column('flooring')
        batch_op.drop_column('total_interior')
        batch_op.drop_column('office_space')
        batch_op.drop_column('topography')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topography', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('office_space', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('total_interior', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('flooring', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('type_style', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('utilities', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('year_built', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('accessibility', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('investment_potential', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('zoning', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('warehouse_size', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('security', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('property_condition', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('loading_docks', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('lot_size', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('parking', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
